### ISSUE TITLE
Problems in start lab

### ISSUE THREAD

**Issue by lelebit** [KatharaFramework/Kathara-Labs#1]
![schermata del 2018-11-12 09-14-45](https://user-images.githubusercontent.com/44964227/48334864-57401f80-e65c-11e8-977b-3dd5ea042dec.png)
Hi guys!
I have a problem with the commands lstart and lclean. The problem stay in a file .py and i haven't any idea to resolve it.
In attach there is a screen about the output on the terminal linux.
My SO is Ubuntu Budgie.
Thank you!

**Comment by Kidel** [comment]
Hi, that's a known issue that we are going to solve possibly this week. 
https://github.com/KatharaFramework/Kathara/issues/24

Please follow the updates on that link.

**Comment by Kidel** [comment]
In the meantine, moving the lab to a path that does NOT contain accented characters should work. Be sure to run `lwipe` if you do that.

**Comment by Kidel** [comment]
@lelebit in the meantine, moving the lab to a path that does NOT contain accented characters should work. Be sure to run `lwipe` if you do that.
