### ISSUE TITLE
Ping not working in simple two-hosts environment

### ISSUE THREAD

**Issue by hjh196** [KatharaFramework/Kathara-Labs#16]
I have installed Kathara version 3.5.1.
I use Ubuntu 22.04.1 LTS, the docker version is 20.10.17. "kathara check" works fine.

I have followed the steps described in "003-kathara-lab_two-hosts.pdf" until step 3 and started two hosts called pc1 and pc2. The ping from pc1 to pc2 (10.0.0.2) fails (100% packet loss).
"arp -n" in pc1 shows that pc2's MAC address has nevertheless been entered correctly into the ARP table of PC1. I also tried tcpdump on pc2 and can see the "Request who-has 10.0.0.2 tell 10.0.0.1" and the response "Reply 10.0.0.2 is-at <mac-addr>", but this is apparently not received by the ping command.

What could be wrong?

**Comment by hjh196** [comment]
Hi Tommaso,

Here's a summary of what I do:

I use a gnome terminal:

> kathara vstart --eth 0:A -n pc1

INFO - ====================== Starting Device ======================
Deploying collision domains...|###########################################| 1/1
Deploying devices...|#####################################################| 1/1

> kathara vstart --eth 0:A -n pc2

INFO - ====================== Starting Device ======================
Deploying collision domains...|###########################################| 1/1
Deploying devices...|#####################################################| 1/1

This opens 2 xterms, pc1 and pc2.

In terminal "pc1":

> ifconfig eth0 10.0.0.1 netmask 255.255.255.0 broadcast 10.0.0.255 up

"ip addr" shows that 10.0.0.1 has been set

In terminal "pc2":

> ifconfig eth0 10.0.0.2 netmask 255.255.255.0 broadcast 10.0.0.255 up

"ip addr" shows that 10.0.0.2 has been set

-> in PC1:
> ping -c 3 10.0.0.2

PING 10.0.0.2 (10.0.0.2) 56(84) bytes of data

--- 10.0.0.2 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 64ms

**** What surprises me is that 10.0.0.2 is in the ARP cache, although it can't be reached by ping ****:

arp -a

? (10.0.0.2) at 5a:80:59:2e:20:fb [ether] on eth0

**Comment by tcaiazzi** [comment]
Hi @hjh196, 

yes the configuration seems correct!

**Comment by hjh196** [comment]
Hi Tommaso,

I tried "systemctl stop firewalld".
"sudo firewall-cmd --state" responded with "not running".
However, the ping still doesn't work...
But your hint to the other open issue is interesting, most probably it is about the same problem.

Regards
hjh196

**Comment by tcaiazzi** [comment]
Hi @hjh196, 

this is very strange since I currently use Ubuntu 22.04 and everything works fine. 

Can you please try to run this [lab](https://github.com/KatharaFramework/Kathara-Labs/tree/master/Basic%20Topics/ARP)?
You only need to enter the lab directory on a terminal and type:
```bash
kathara lstart
```
Then go into the shell of `pc1` and ping `pc2`:
```bash
ping 200.1.1.7
```

Let me know if it works, although we can organize a call to fix your problem. 

Cheers, 
Tommaso

**Comment by hjh196** [comment]
I tried the lab. Unfortunately, it still doesn't work...
The matter is not urgent for me, I'm just playing around a bit.
Maybe, I should mention that I'm using an ubuntu system which is already running as a VM. Could the problem somehow be related to nested virtualization problems?

**Comment by tcaiazzi** [comment]
No, it should work also on a VM without problems. 

Can I ask how you installed Docker?

**Comment by hjh196** [comment]
It's been a while since I did that, but I assume I used the usual way via "apt install".
Maybe I'll have to compare the behaviour on another system. Or is there a public cloud where Kathara can be used?

**Comment by hjh196** [comment]
The docker version is 20.10.17, build 100c70180f.
I'll need a bit of time to do the reinstall.

**Comment by tcaiazzi** [comment]
The Docker version seems good. 

Let me know if the error persists after the reinstall.

**Comment by hjh196** [comment]
In the meantime, I tried on another computer, also with Ubuntu. That one worked.
Reinstallation on the first system will be my next step.

**Comment by tcaiazzi** [comment]
Good news!

Let me know when you try on the first system!

**Comment by tcaiazzi** [comment]
I am closing this issue for staling reasons. Please feel free to reopen if you have any problems.
