### ISSUE TITLE
Netkit lab 'Load balancer': connection refused from client1 to server2

### ISSUE THREAD

**Issue by Francesco9932** [KatharaFramework/Kathara-Labs#17]
Hi, 

In the netkit lab 'Load balancer' i found an error when i tried to connect to server apache with the command 'links 100.0.0.2' from client1 to server2. The server2's apache server i can tell further i checked and it is running on the machine.

To startup the lab i used the wsl2 engine as backend. How i can fix this issue? Thanks in advance 

For a better understanding of the problem described above I have also added some screenshots of the command output
![Immagine 2023-01-16 143229](https://user-images.githubusercontent.com/72614773/212692638-2fb51766-9d40-4f33-a981-9cdf9e332e52.png)

**Comment by Skazza94** [comment]
Hi @Francesco9932,
are you referring to the lab [Application Level/LoadBalancerRandom](https://github.com/KatharaFramework/Kathara-Labs/tree/master/Application%20Level/LoadBalancerRandom)? I just tested it and all the three servers respond correctly.

If it is another lab, please specify a link or upload a zip file. 

Keep in mind that, as stated in the README, NetKit labs are not tested with Kathará so they might not work properly.

Mariano.

**Comment by georgelzrc** [comment]
Hi, I had the same problem as @Francesco9932 , it worked on my machine by modyfing these lines in  **ws_random.startup** : 

iptables --table nat --append PREROUTING --destination 100.0.0.2 -p tcp --dport 80 --match statistic --mode random --probability 0.33 --jump DNAT --to-destination 10.0.0.1:80
iptables --table nat --append PREROUTING --destination 100.0.0.2 -p tcp --dport 80 --match statistic --mode random --probability 0.5 --jump DNAT --to-destination 10.0.0.2:80
iptables --table nat --append PREROUTING --destination 100.0.0.2 -p tcp --dport 80 --jump DNAT --to-destination 10.0.0.3:80

i replaced **iptables** with **iptables-legacy** and clients started reaching the servers.

George

**Comment by Francesco9932** [comment]
Hi @Skazza94, 
Yes i'm referring to the lab Application Level/LoadBalancerRandom and with the replacing suggested by @georgelzrc now the client reaches the server.
