### ISSUE TITLE
Kathara lstart needs to allow sharing of the shared folder on each individual machine in kathara labs

### ISSUE THREAD

**Issue by Francesco9932** [KatharaFramework/Kathara-Labs#18]
Hi,

When i lunch a kathara lab (not one in particular) with hyper-v backend engine  the kathara lstart need to allow sharing of the shared folder on each individual machine. Once this is done, the lab works correctly without further problems, only that in labs with many machines this behavior is a bit annoying, how i can fix it? Thanks in advance!

For a better understanding of the problem described above I have also added some screenshots of the issue.

![Immagine 2023-01-16 142749](https://user-images.githubusercontent.com/72614773/212694479-9b93afd4-c93d-49e7-ad8f-5cd50eb66142.png)

**Comment by Skazza94** [comment]
Hi @Francesco9932,
this is not a Kathará-related problem. Docker Desktop with Hyper-V requires to manually allow the volume sharing for each folder for security reasons.
My suggestion is permanently to switch to WSL2, unless Hyper-V is the only way to make things work (e.g. for the datacenter lab).

I'm closing the issue.

Mariano.

**Comment by tcaiazzi** [comment]
Hi @Francesco9932,

alternatively, you can allow Docker Desktop to access all the `C:` drive.

You can configure it going into the `Settings` of Docker Desktop, then open the `Resources` tab and click to `File Sharing`. Here you can add all the `C:` drive or only the directory you use for working with Kathará (e.g your labs directory). 

Here a [tutorial](https://medium.com/analytics-vidhya/sharing-windows-folders-for-containers-4539f7ed2acf) you can follow. 

Cheers, 
Tommaso
