### ISSUE TITLE
ERROR STARTING MY KATHARA (CORRECT) LAB

### ISSUE THREAD

**Issue by sim94** [KatharaFramework/Kathara-Labs#2]
I've a problem with a lab created by me. 
So, i've created a lab with some specifies, i've created all the right files to run a lab (the lab works for sure), but when i execute it on kathara, the framework doesn't run and i see this:

"Error response from daemon: No such container: netkit_1000_r1
Error response from daemon: No such container: netkit_1000_r2
Error response from daemon: No such container: netkit_1000_l4switch
Error response from daemon: No such container: netkit_1000_ws1
Error response from daemon: No such container: netkit_1000_pc
Error response from daemon: No such container: netkit_1000_ws2
Error: failed to start containers: netkit_1000_r1, netkit_1000_r2, netkit_1000_l4switch, netkit_1000_ws1, netkit_1000_pc, netkit_1000_ws2
Traceback (most recent call last):
  File "/opt/kathara/bin/python/lstart.py", line 141, in <module>
    (commands, startup_commands, exec_commands) = nc.create_commands(filtered_machines, links, options, metadata, lab_path, args.execbash, no_machines_tmp=(len(machine_name_args) >= 1))
  File "/opt/kathara/bin/python/netkit_commons.py", line 316, in create_commands
    startup_commands.append(u.replace_multiple_items(repls, exec_template))
  File "/opt/kathara/bin/python/utils.py", line 21, in replace_multiple_items
    return functools.reduce(lambda a, kv: a.replace(*kv), repls, string)
  File "/opt/kathara/bin/python/utils.py", line 21, in <lambda>
    return functools.reduce(lambda a, kv: a.replace(*kv), repls, string)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 146: ordinal not in range(128)"

Why? 

P.S. i've created the files in windows enviroment and then i pasted them on VM with ubuntu, i don't know if it can be a reason.

**Comment by lorenzo93** [comment]
Please, update your Katharà setup to the newest version (released just 1 hour ago)

This is a well know bug fixed in last release.

**Comment by sim94** [comment]
ok thanks a lot.

**Comment by lorenzo93** [comment]
I'll close this issue.
If there are further problems, feel free to open it again!
