### ISSUE TITLE
Bind fails to start in Small Internet with DNS and Webserver

### ISSUE THREAD

**Issue by fstachura** [KatharaFramework/Kathara-Labs#25]
**Describe the bug**
Bind fails to start in labs that use bind - `/etc/init.d/bind` points at `/etc/init.d/bind9` which does not exist.

**To Reproduce**
1. Download and unzip https://github.com/KatharaFramework/Kathara-Labs/blob/master/Labs%20Integrating%20Several%20Technologies/Small%20Internet%20with%20DNS%20and%20Webserver/small-internet-w-dns-webserver.zip
2. Run `kathara lstart`

**Expected behavior**
Bind starts in relevant containers. 

**Screenshots**
![image](https://github.com/KatharaFramework/Kathara-Labs/assets/55913800/205d18b6-a74a-4057-bc95-bca2489688b6)

Similar problem with `zebra` in the same lab:

![image](https://github.com/KatharaFramework/Kathara-Labs/assets/55913800/92004bb7-5150-471e-9184-c80823819513)

<details>
<summary>"check" Command Output</summary>

```
*       Current Manager is: Docker (Kathara)
*       Manager version is: 24.0.2
*       Python version is: 3.10.7 (main, Dec 28 2022, 15:08:11) [GCC 12.2.0]
*       Kathara version is: 3.5.5
*       Operating System version is: Linux-6.1.34-1-lts-x86_64
*       Trying to run `Hello World` container...
Deploying devices...|#################################################################################################################################################################################################################| 1/1
*       Container run successfully.
Deleting devices...|##################################################################################################################################################################################################################| 1/1
```

Image versions:
```
% sudo docker image ls | grep kathara
kathara/p4                    latest     102cfaad1543   10 days ago    12.4GB
kathara/linux-build-pkg       latest     f6a4880b9ad4   2 months ago   1.29GB
kathara/p4                    <none>     ad31a1540f1a   6 months ago   11.7GB
kathara/quagga                latest     27f4e3584706   6 months ago   819MB
```

</details>

**Comment by tcaiazzi** [comment]
I also found that something is broken with the routing. Tomorrow I will investigate and (hopefully :innocent:)  fix the problem.

**Comment by tcaiazzi** [comment]
Hi @fstachura, 

I investigated further the problem and I found that the issue is related to something that changes after we updated the base image from `Debian 10`  to `Debian 11`.

We will rollback the `latest` images to `Debian 10` while we are searching for a solution. 

In the meanwhile, you can use all the labs by adding the tag `:debia10` to `quagga` and `base` images.

Many thanks,
Tommaso

**Comment by tcaiazzi** [comment]
I pushed working images (with `Debian 10`) to the Docker Hub. 

So everything should work fine now.

Let me know if you find any problem!

Many thanks,
Tommaso

**Comment by fstachura** [comment]
I can confirm that bind works on the base image now. Thanks!
