### ISSUE TITLE
Created a pull request for dhcp scenario

### ISSUE THREAD

**Issue by AlexFalzone** [KatharaFramework/Kathara-Labs#39]
As the title suggests, I created a pull request for adding a simple scenario with a DHCP server.

Use Case:
1. kathara lstart -d "directory where the lab is present"
2. ping pc1 from pc2 (or vice versa)

**Comment by tcaiazzi** [comment]
Hi @AlexFalzone, 

Many thanks for the PR, and for contributing to Kathará :heart_eyes: 

I'm closing this issue, so we can continue the discussion directly in the PR.
