### ISSUE TITLE
NetKit lab 'MPLS forwarding' : lstart not working on Kathara, missing interface on device

### ISSUE THREAD

**Issue by ramonahyde** [KatharaFramework/Kathara-Labs#7]
Hello!

I want to start this old lab called *MPLS forwarding*, using Kathara : https://web.archive.org/web/20171119083600if_/http://wiki.netkit.org/netkit-labs/netkit-labs_advanced-topics/netkit-lab_mpls-forwarding/netkit-lab_mpls-forwarding.tar.gz

I'm getting this error:

```sh
$ kathara lstart
INFO - ======================= Starting Lab ========================
CRITICAL - Interface 0 missing on device ler1.
```

`ler1` startup code : 
```sh
ifconfig eth1 192.168.0.2 netmask 255.255.255.0 broadcast 192.168.0.255 up
ifconfig eth2 172.16.0.2 netmask 255.255.255.0 broadcast 172.16.0.255 up

#mpls modules
modprobe mpls4
modprobe mplsbr
modprobe mpls_tunnel


#ip traffic between hosta and hostc
route add -net 172.16.2.0 netmask 255.255.255.0 gw 172.16.0.3 dev eth2



#**************** MPLS TRAFFIC FROM HOSTA TO HOSTB MPLS TRAFFIC **************************
#This instruction creates a new entry in the NHLFE table in order to add (push) label 1000 to
#the packets directed to hostb and forward them to 172.16.0. address (nexthop) using eth2 ler1 interface

mpls nhlfe add key 0 instructions push gen 1000 nexthop eth2 ipv4 172.16.0.3

#label binding: packets directed to 10.0.0.2 routed by 172.16.0.3 are a fec, identified by label
#0x2, returned by previous instruction

ip route add 10.0.0.2/32 via 172.16.0.3 mpls 0x2





#**************** MPLS TRAFFIC FROM HOSTB TO HOSTA **************************
#eth2 is set to receive mpls traffic
mpls labelspace set dev eth2 labelspace 0

#add an entry on ilm table in order to list the incaming label (2001)
mpls ilm add label gen 2001 labelspace 0


#This instruction creates a new entry in the NHLFE table in order to 
#forward packets to 192.168.0.1 address (nexthop) using eth2 ler1 interface
mpls nhlfe add key 0 instructions nexthop eth1 ipv4 192.168.0.1

#label 2001 is removed from packet
mpls xc add ilm_label gen 2001 ilm_labelspace 0 nhlfe_key 0x3
```

I'm aware that all Netkit labs have been not tested, but I really need it to work as it is requested in my Network class. I have no clue for now and I couldn't find a similar lab in the repo.

In Network class, we're using Netkit but I couldn't install it properly on my machine. Kathara was easy to install though. So far I managed to start and use old labs seen in class but not this one...  

Thanks in advance.

**Comment by Skazza94** [comment]
Hi @ramonahyde,
sorry for the late reply. There are some differences between NetKit and Kathará, and what you found is one of them. In Kathará, due to Docker limitations, device interface numbers must start at 0 and be sequentially incremented.
In this case, in the `lab.conf`, you have:
```
ler1[1]="A"
ler1[2]="B"

lsr[2]="B"
lsr[3]="C"

ler2[3]="C"
ler2[0]="D"
```

As you can see `ler1` misses interface 0, `lsr2` misses 0 and 1, and `ler2` misses 1 and 2. So, a fixed `lab.conf` that works in Kathará is the following:
```
ler1[0]="A"
ler1[1]="B"

lsr[0]="B"
lsr[1]="C"

ler2[1]="C"
ler2[0]="D"
```

However, keep in mind that you also have to change the `.startup` files to match the `ethX` with the corresponding interface number.

Hope this helps!
Mariano.
